export enum AuthorizeActionType {
    
    LOGIN = 'LOGIN',
    SUBSCRIBE_AUTH_STATE_CHANGE = 'SUBSCRIBE_AUTH_STATE_CHANGE',
    FETCH_USER_REGISTER_TOKEN = 'FETCH_USER_REGISTER_TOKEN',
    SET_USER_REGISTER_TOKEN = 'SET_USER_REGISTER_TOKEN',
    LOGOUT = 'LOGOUT',
    SIGNUP = 'SIGNUP',
    UPDATE_PASSWORD = 'UPDATE_PASSWORD'
}
