export enum AuthorizeActionType {
    
    LOGIN = 'LOGIN',
    SUBSCRIBE_AUTH_STATE_CHANGE = 'SUBSCRIBE_AUTH_STATE_CHANGE',
    ASYNC_FETCH_USER_REGISTER_TOKEN = 'ASYNC_FETCH_USER_REGISTER_TOKEN',
    ASYNC_VERITY_USER_REGISTER_CODE = 'ASYNC_VERITY_USER_REGISTER_CODE',
    SET_USER_REGISTER_TOKEN = 'SET_USER_REGISTER_TOKEN',
    LOGOUT = 'LOGOUT',
    SIGNUP = 'SIGNUP',
    UPDATE_PASSWORD = 'UPDATE_PASSWORD',
    SET_SIGNUP_STEP = 'SET_SIGNUP_STEP'
}
