export enum CircleActionType {

    ADD_CIRCLE = 'ADD_CIRCLE',
    DELETE_CIRCLE = 'DELETE_CIRCLE',
    UPDATE_CIRCLE = 'UPDATE_CIRCLE',
    ADD_LIST_CIRCLE = 'ADD_LIST_CIRCLE',
    CLEAR_ALL_CIRCLES = 'CLEAR_ALL_CIRCLES',
    OPEN_CIRCLE_SETTINGS = 'OPEN_CIRCLE_SETTINGS',
    CLOSE_CIRCLE_SETTINGS = 'CLOSE_CIRCLE_SETTINGS',
    ADD_FOLLOWING_USER = 'ADD_FOLLOWING_USER',
    DELETE_FOLLOWING_USER = 'DELETE_FOLLOWING_USER',
    UPDATE_USER_TIE = 'UPDATE_USER_TIE',
    ADD_USER_TIE_LIST = 'ADD_USER_TIE_LIST',
    ADD_USER_TIED_LIST = 'ADD_USER_TIED_LIST',
    DELETE_USER_FROM_CIRCLE = 'DELETE_USER_FROM_CIRCLE',
    SHOW_SELECT_CIRCLE_BOX = 'SHOW_SELECT_CIRCLE_BOX',
    HIDE_SELECT_CIRCLE_BOX = 'HIDE_SELECT_CIRCLE_BOX',
    SET_SELECTED_CIRCLES_USER_BOX_COMPONENT = 'SET_SELECTED_CIRCLES_USER_BOX_COMPONENT',
    REMOVE_SELECTED_CIRCLES_USER_BOX_COMPONENT = 'REMOVE_SELECTED_CIRCLES_USER_BOX_COMPONENT',
    OPEN_SELECT_CIRCLES_USER_BOX_COMPONENT = 'OPEN_SELECT_CIRCLES_USER_BOX_COMPONENT',
    CLOSE_SELECT_CIRCLES_USER_BOX_COMPONENT = 'CLOSE_SELECT_CIRCLES_USER_BOX_COMPONENT',
    SHOW_FOLLOWING_USER_LOADING = 'SHOW_FOLLOWING_USER_LOADING',
    HIDE_FOLLOWING_USER_LOADING = 'HIDE_FOLLOWING_USER_LOADING'

}
