export enum CommentActionType {
    
    ADD_COMMENT = 'ADD_COMMENT',
    ADD_COMMENT_LIST = 'ADD_COMMENT_LIST',
    DELETE_COMMENT = 'DELETE_COMMENT',
    CLEAR_ALL_DATA_COMMENT = 'CLEAR_ALL_DATA_COMMENT',
    UPDATE_COMMENT = 'UPDATE_COMMENT',
    CLOSE_COMMENT_EDITOR = 'CLOSE_COMMENT_EDITOR',
    OPEN_COMMENT_EDITOR = 'OPEN_COMMENT_EDITOR',
    DB_FETCH_COMMENTS = 'DB_FETCH_COMMENTS',
}