export enum GlobalActionType {

    PROGRESS_CHANGE = 'PROGRESS_CHANGE',
    DEFAULT_DATA_DISABLE = 'DEFAULT_DATA_DISABLE',
    DEFAULT_DATA_ENABLE = 'DEFAULT_DATA_ENABLE',
    LOADING = 'LOADING',
    HIDE_MESSAGE_GLOBAL = 'HIDE_MESSAGE_GLOBAL',
    SHOW_MESSAGE_GLOBAL = 'SHOW_MESSAGE_GLOBAL',
    SHOW_NORMAL_MESSAGE_GLOBAL = 'SHOW_NORMAL_MESSAGE_GLOBAL',
    SET_HEADER_TITLE = 'SET_HEADER_TITLE',
    SHOW_TOP_LOADING = 'SHOW_TOP_LOADING',
    HIDE_TOP_LOADING = 'HIDE_TOP_LOADING',
    SHOW_MASTER_LOADING = 'SHOW_MASTER_LOADING',
    HIDE_MASTER_LOADING = 'HIDE_MASTER_LOADING',
    SHOW_SEND_FEEDBACK = 'SHOW_SEND_FEEDBACK',
    HIDE_SEND_FEEDBACK = 'HIDE_SEND_FEEDBACK',
    TEMP = 'TEMP',
    CLEAR_ALL_GLOBAL = 'CLEAR_ALL_GLOBAL',
    OPEN_POST_WRITE = 'OPEN_POST_WRITE',
    CLOSE_POST_WRITE = 'CLOSE_POST_WRITE'

}