 export enum PostActionType {

    ADD_IMAGE_POST = 'ADD_IMAGE_POST',
    HAS_MORE_DATA_STREAM = 'HAS_MORE_DATA_STREAM',
    NOT_MORE_DATA_STREAM = 'NOT_MORE_DATA_STREAM',
    REQUEST_PAGE_STREAM = 'REQUEST_PAGE_STREAM',
    LAST_POST_STREAM = 'LAST_POST_STREAM',
    HAS_MORE_DATA_PROFILE = 'HAS_MORE_DATA_PROFILE',
    NOT_MORE_DATA_PROFILE = 'NOT_MORE_DATA_PROFILE',
    REQUEST_PAGE_PROFILE = 'REQUEST_PAGE_PROFILE',
    LAST_POST_PROFILE = 'LAST_POST_PROFILE',
    ADD_VIDEO_POST = 'ADD_VIDEO_POST',
    ADD_POST = 'ADD_POST',
    UPDATE_POST = 'UPDATE_POST',
    UPDATE_POST_COMMENTS = 'UPDATE_POST_COMMENTS',
    UPDATE_POST_VOTES = 'UPDATE_POST_VOTES',
    DELETE_POST = 'DELETE_POST',
    ADD_LIST_POST = 'ADD_LIST_POST',
    CLEAR_ALL_DATA_POST = 'CLEAR_ALL_DATA_POST'
}
