export enum UserActionType {

    ADD_USERS = 'ADD_USERS',
    ADD_USER_INFO = 'ADD_USER_INFO',
    UPDATE_USER_INFO = 'UPDATE_USER_INFO',
    USER_INFO = 'USER_INFO',
    CLEAR_ALL_DATA_USER = 'CLEAR_ALL_DATA_USER',
    OPEN_EDIT_PROFILE = 'OPEN_EDIT_PROFILE',
    CLOSE_EDIT_PROFILE = 'CLOSE_EDIT_PROFILE',
    ADD_PEOPLE_INFO = 'ADD_PEOPLE_INFO'
}