export enum UserSettingActionType {

    SET_USER_SETTING = 'SET_USER_SETTING',
    DB_UPDATE_USER_SETTING = 'DB_UPDATE_USER_SETTING',
    DB_FETCH_USER_SETTING = 'DB_FETCH_USER_SETTING',
    CLEAR_ALL_USER_SETTING = 'CLEAR_ALL_USER_SETTING'
}