/* post actions */
export const ADD_IMAGE_POST = 'ADD_IMAGE_POST'
export const ADD_VIDEO_POST = 'ADD_VIDEO_POST'
export const ADD_POST = 'ADD_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const DELETE_POST = 'DELETE_POST'
export const ADD_LIST_POST = 'ADD_LIST_POST'
export const CLEAR_ALL_DATA_POST = 'CLEAR_ALL_DATA_POST'


/* image gallery actions */
export const OPEN_IMAGE_GALLERY = 'OPEN_IMAGE_GALLERY'
export const ADD_IMAGE_GALLERY = 'ADD_IMAGE_GALLERY'
export const ADD_IMAGE_LIST_GALLERY = 'ADD_IMAGES_LIST_GALLERY'
export const IMAGE_SELECT_GALLERY = 'IMAGE_SELECT_GALLERY'
export const CLEARS_SELECT_IMAGE_GALLERY = 'CLEARS_SELECT_IMAGE_GALLERY'
export const CLEAT_ALL_DATA_IMAGE_GALLERY = 'CLEAT_ALL_DATA_IMAGE_GALLERY'
export const DELETE_IMAGE = 'DELETE_IMAGE'
export const SET_IMAGE_URL = 'SET_IMAGE_URL'
export const SEND_IMAGE_REQUEST = 'SEND_IMAGE_REQUEST'

/* image uploader actions */
export const OPEN_IMAGE_UPLOADER = 'OPEN_IMAGE_UPLOADER'
export const OPEN_IMAGE_EDITOR = 'OPEN_IMAGE_EDITOR'

/* comment actions */
export const ADD_COMMENT = 'ADD_COMMENT'
export const ADD_COMMENT_LIST = 'ADD_COMMENT_LIST'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const CLEAR_ALL_DATA_COMMENT = 'CLEAR_ALL_DATA_COMMENT'
export const UPDATE_COMMENT = 'UPDATE_COMMENT'
export const CLOSE_COMMENT_EDITOR = 'CLOSE_COMMENT_EDITOR'
export const OPEN_COMMENT_EDITOR = 'OPEN_COMMENT_EDITOR'


/* vote actions */
export const ADD_VOTE = 'ADD_VOTE'
export const DELETE_VOTE = 'DELETE_VOTE'
export const ADD_VOTE_LIST = 'ADD_VOTE_LIST'
export const CLEAR_ALL_DATA_VOTE = 'CLEAR_ALL_DATA_VOTE'


/* users action */
export const ADD_USERS = 'ADD_USERS'
export const ADD_USER_INFO = 'ADD_USER_INFO'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const USER_INFO = 'USER_INFO'
export const CLEAR_ALL_DATA_USER = 'CLEAR_ALL_DATA_USER'
export const OPEN_EDIT_PROFILE = 'OPEN_EDIT_PROFILE'
export const CLOSE_EDIT_PROFILE = 'CLOSE_EDIT_PROFILE'
export const ADD_PEOPLE_INFO = 'ADD_PEOPLE_INFO'

/* circle actions */
export const ADD_CIRCLE = 'ADD_CIRCLE'
export const DELETE_CIRCLE = 'DELETE_CIRCLE'
export const UPDATE_CIRCLE = 'UPDATE_CIRCLE'
export const ADD_LIST_CIRCLE = 'ADD_LIST_CIRCLE'
export const CLEAR_ALL_CIRCLES = 'CLEAR_ALL_CIRCLES'
export const OPEN_CIRCLE_SETTINGS = 'OPEN_CIRCLE_SETTINGS'
export const CLOSE_CIRCLE_SETTINGS = 'CLOSE_CIRCLE_SETTINGS'
export const ADD_FOLLOWING_USER = 'ADD_FOLLOWING_USER'
export const DELETE_FOLLOWING_USER = 'DELETE_FOLLOWING_USER'

/* notify actions */
export const ADD_NOTIFY = 'ADD_NOTIFY'
export const ADD_NOTIFY_LIST = 'ADD_NOTIFY_LIST'
export const DELETE_NOTIFY = 'DELETE_NOTIFY'
export const SEEN_NOTIFY = 'SEEN_NOTIFY'
export const CLEAR_ALL_DATA_NOTIFY = 'CLEAR_ALL_DATA_NOTIFY'

/* authorize actions */
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SIGNUP = 'SIGNUP'
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD'

/* file actions */
export const UPLOAD_FILE = 'UPLOAD_FILE'
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR'
export const UPLOAD_FILE_COMPLETE = 'UPLOAD_FILE_COMPLETE'
export const DOWNLOAD_FILE = 'DOWNLOAD_FILE'


/* global actions */
export const PROGRESS_CHANGE = 'PROGRESS_CHANGE'
export const DEFAULT_DATA_DISABLE = 'DEFAULT_DATA_DISABLE'
export const DEFAULT_DATA_ENABLE = 'DEFAULT_DATA_ENABLE'
export const LOADING = 'LOADING'
export const HIDE_MESSAGE_GLOBAL = 'HIDE_MESSAGE_GLOBAL'
export const SHOW_ERROR_MESSAGE_GLOBAL = 'SHOW_ERROR_MESSAGE_GLOBAL'
export const SHOW_NORMAL_MESSAGE_GLOBAL = 'SHOW_NORMAL_MESSAGE_GLOBAL'
export const SHOW_SEND_REQUEST_MESSAGE_GLOBAL = 'SHOW_SEND_REQUEST_MESSAGE_GLOBAL'
export const SHOW_REQUEST_SUCCESS_MESSAGE_GLOBAL = 'SHOW_REQUEST_SUCCESS_MESSAGE_GLOBAL'
export const SET_HEADER_TITLE = 'SET_HEADER_TITLE'
export const SHOW_TOP_LOADING = 'SHOW_TOP_LOADING'
export const HIDE_TOP_LOADING = 'HIDE_TOP_LOADING'
export const TEMP = 'TEMP'
