export enum CircleActionType {
    
    ADD_CIRCLE = 'ADD_CIRCLE',
    DELETE_CIRCLE = 'DELETE_CIRCLE',
    UPDATE_CIRCLE = 'UPDATE_CIRCLE',
    ADD_LIST_CIRCLE = 'ADD_LIST_CIRCLE',
    CLEAR_ALL_CIRCLES = 'CLEAR_ALL_CIRCLES',
    OPEN_CIRCLE_SETTINGS = 'OPEN_CIRCLE_SETTINGS',
    CLOSE_CIRCLE_SETTINGS = 'CLOSE_CIRCLE_SETTINGS',
    ADD_FOLLOWING_USER = 'ADD_FOLLOWING_USER',
    DELETE_FOLLOWING_USER = 'DELETE_FOLLOWING_USER',
}