export enum GlobalActionType {

    PROGRESS_CHANGE = 'PROGRESS_CHANGE',
    DEFAULT_DATA_DISABLE = 'DEFAULT_DATA_DISABLE',
    DEFAULT_DATA_ENABLE = 'DEFAULT_DATA_ENABLE',
    LOADING = 'LOADING',
    HIDE_MESSAGE_GLOBAL = 'HIDE_MESSAGE_GLOBAL',
    SHOW_ERROR_MESSAGE_GLOBAL = 'SHOW_ERROR_MESSAGE_GLOBAL',
    SHOW_NORMAL_MESSAGE_GLOBAL = 'SHOW_NORMAL_MESSAGE_GLOBAL',
    SHOW_SEND_REQUEST_MESSAGE_GLOBAL = 'SHOW_SEND_REQUEST_MESSAGE_GLOBAL',
    SHOW_REQUEST_SUCCESS_MESSAGE_GLOBAL = 'SHOW_REQUEST_SUCCESS_MESSAGE_GLOBAL',
    SET_HEADER_TITLE = 'SET_HEADER_TITLE',
    SHOW_TOP_LOADING = 'SHOW_TOP_LOADING',
    HIDE_TOP_LOADING = 'HIDE_TOP_LOADING',
    TEMP = 'TEMP',
    OPEN_POST_WRITE = 'OPEN_POST_WRITE',
    CLOSE_POST_WRITE = 'CLOSE_POST_WRITE'

}