export enum ImageGalleryActionType {

    ADD_IMAGE_GALLERY = 'ADD_IMAGE_GALLERY',
    ADD_IMAGE_LIST_GALLERY = 'ADD_IMAGES_LIST_GALLERY',
    CLEAT_ALL_DATA_IMAGE_GALLERY = 'CLEAT_ALL_DATA_IMAGE_GALLERY',
    DELETE_IMAGE = 'DELETE_IMAGE',
    SET_IMAGE_URL = 'SET_IMAGE_URL',
    SEND_IMAGE_REQUEST = 'SEND_IMAGE_REQUEST'
}