
 export enum postActionType {
    ADD_IMAGE_POST = "ADD_IMAGE_POST",
    ADD_VIDEO_POST = "ADD_VIDEO_POST",
    ADD_POST = "ADD_POST",
    UPDATE_POST = "UPDATE_POST",
    DELETE_POST = "DELETE_POST",
    ADD_LIST_POST = "ADD_LIST_POST",
    CLEAR_ALL_DATA_POST = "CLEAR_ALL_DATA_POST"
};

